# -*- coding: utf-8 -*-
"""Python coursework 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yn4Z_LmuKlVKWpLMVxhLo2zjRKjooyMg

# **Matplotlib**
"""

import numpy as np
x = np.arange(0,100)
y = x*2
z = x**2

print(y)
print(z)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.plot(x,y)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_title('Line Plot')

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
bx = fig.add_axes([0.2,0.5,.4,.4])

fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
bx = fig.add_axes([0.2, 0.5, 0.4, 0.4])
bx.plot(x, y)
ax.plot(x, z)
plt.show()

fig, axes = plt.subplots(nrows=1, ncols=2)
axes[0]
axes[1]
plt.show()

fig, axes = plt.subplots(nrows=1, ncols=2)
axes[0].plot(x, y,'--')
axes[1].plot(x, z,color='red')
plt.show()

"""# **Seaborn**"""

import seaborn as sns
sns.set_style('whitegrid')
penguins = sns.load_dataset('penguins')
penguins.head()

sns.barplot(x='species', y='flipper_length_mm', data=penguins,  hue='species')
plt.show()

sns.violinplot(x='species', y='flipper_length_mm', data=penguins, hue='species')
plt.show()

sns.pairplot(penguins, hue='species')
plt.show()

numerical_cols = penguins.select_dtypes(include=['number']).columns
correlation_matrix = penguins[numerical_cols].corr()

sns.heatmap(correlation_matrix, annot=True)
plt.show()

sns.scatterplot(data=penguins, x='bill_length_mm', y='bill_depth_mm', hue='species')
plt.show()

